name: "DefectDojo Upload Reports"

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

env:
  DEFECTDOJO_API_TOKEN: ${{ secrets.DEFECTDOJO_API_TOKEN }}
  DEFECTDOJO_IMPORT_API_URL: ${{ secrets.DEFECTDOJO_IMPORT_API_URL }}

jobs:
  upload_reports:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout PR commit
        uses: actions/checkout@v4
      - name: Install requirements
        run: pip3 install requests
      - name: debug
        run: ls -la
      - name: Get reports
        run: python3 .github/workflows/getghdata.py
      # - name: Upload reports
      #   run: python3 .github/workflows/upload.py